[book]
authors = ["Peter Heiss"]
language = "en"
multilingual = false
src = "src"
title = "GTFO Knowledge Database"
description = "Everything you should or wants to know about GTFO"

[output.html]
additional-css = ["theme/style.css"]
additional-js = ["theme/sidebar.js"]